### PR TITLE
User experince updates

### PR DESCRIPTION
**Pull request by jjburbridge**
- Allow users to write predefined queries in config of plugin that add buttons with queries
  - On first run of query check what actions will happen (does not gather references)
image (1)

 - show message when query returns no results
image

- add info icon to status badges to highlight tooltip:
image

### CODE REVIEW

**Comment by SimeonGriggs** [comment]
Something I meant to do forever!

1. I'd change the "Useful queries" title to "Saved queries"
2. I don't love the _look_ of the info icon in the badge ... but I don't have good alternative ideas.

**Comment by jjburbridge** [comment]
> Something I meant to do forever!
> 
> 1. I'd change the "Useful queries" title to "Saved queries"
> 2. I don't love the _look_ of the info icon in the badge ... but I don't have good alternative ideas.

@SimeonGriggs I did think about saved queries but that made me this it would be something that you could add to in the studio, How about "Predefined queries"?

**Comment by thebiggianthead** [comment]
> @SimeonGriggs I did think about saved queries but that made me this it would be something that you could add to in the studio, How about "Predefined queries"?

I think "predefined queries" works well – I'd go for that. Any thoughts on the icon? Think I agree with Simeon on this one.

**Comment by jjburbridge** [comment]
@thebiggianthead and @SimeonGriggs  there is HelpCircleIcon
image

**Comment by thebiggianthead** [comment]
Just pushed an update to the branch @jjburbridge with a change on the badge (more about spacing than the icon itself). Also adjusted the messaging a bit for empty queries to simplify it. Thoughts?

**Review by thebiggianthead — APPROVED** [review]

**Pull request merged**
